### ISSUE TITLE
Upload this into pypi?

### ISSUE THREAD

**Issue by clouduan** [1033020837/GitIgnoreGenerator#1]
This tool really satisfies requirements especially when I create my repository in local!

One suggestion, you can upload this into [Pypi](https://pypi.org/). In that way we just install it using pip and don't have to clone the repo every time...

BTW, pls forgive my poor English in any case :neckbeard: ...

**Comment by 1033020837** [comment]
I do not know how to upload it to Pypi,lol

**Comment by clouduan** [comment]
Read the pypi manual and you are done

**Comment by clouduan** [comment]
I am the earliest user, COOL!

**Comment by 1033020837** [comment]
maybe you will be the only.lol
